language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

jdk:
- oraclejdk8

script:
- ./gradlew test

before_deploy:
  - ./gradlew assembleDebug

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: $GITHUB_TOKEN
    file: RondoApp/build/outputs/apk/debug/RondoApp-debug.apk
    draft: true
    on:
      tags: true
