language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
jdk:
- oraclejdk8
script:
- "./gradlew test"
before_deploy:
- "./gradlew assembleDebug"
- ls RondoApp/build/outputs/apk/debug/RondoApp-debug.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
    secure: 
  file: "RondoApp/build/outputs/apk/debug/RondoApp-debug.apk"
  draft: true
  on:
    repo: Leanplum/Rondo-Android
