language: android
dist: bionic
jdk: openjdk17

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools;35.0.0
    - platforms;android-35
    - extras;android;m2repository

  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  # Decrypt keystore
  - mkdir -p keystore
  - openssl aes-256-cbc -K $encrypted_3e25ea35f95b_key -iv $encrypted_3e25ea35f95b_iv -in signingkey.jks.enc -out keystore/signingkey.jks -d

branches:
  except:
  - /^untagged/
script:
  - "./gradlew test"
before_deploy:
  - "./gradlew assembleProdRelease"
  - export TRAVIS_TAG=$LEANPLUM_SDK_VERSION
deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "RondoApp/build/outputs/apk/prod/release/RondoApp-prod-release.apk"
  name: "Android SDK $LEANPLUM_SDK_VERSION"
  dpl_version: 1.10.16
#  tag: "$LEANPLUM_SDK_VERSION"
  on:
    branch: master
    condition: '-n "$LEANPLUM_SDK_VERSION"'

after_deploy:
  - GH_REPO=github.com/Leanplum/Rondo-Android.git
  - REPO_NAME=Rondo-Android
  - git clone https://${GH_REPO}
  - cd ${REPO_NAME}
  - git config user.email "travis@travis-ci.com"
  - git config user.name "travis"
  - git commit --allow-empty -m "Rondo released with SDK version $LEANPLUM_SDK_VERSION"
  - git push https://${ACCESS_TOKEN}@${GH_REPO} HEAD:master
