language: android

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - BUILD_API=31
    - BUILD_TOOLS=31.0.0
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/cmdline-tools/latest
    # PATH order is important, the 'emulator' script exists in more than one place
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

jdk:
  - oraclejdk11

android:
  components:
    - tools

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  # Install cmdline-tools (older tools doesn't support Java 11)
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
  # Decrypt keystore
  - mkdir -p keystore
  - openssl aes-256-cbc -K $encrypted_3e25ea35f95b_key -iv $encrypted_3e25ea35f95b_iv -in signingkey.jks.enc -out keystore/signingkey.jks -d

before_script:
  # Install Android SDK
  - echo 'count=0' > /home/travis/.android/repositories.cfg # avoid harmless sdkmanager warning
  - echo y | ${TOOLS}/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "build-tools;$BUILD_TOOLS" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "platforms;android-$BUILD_API" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "extras;android;m2repository" >/dev/null

branches:
  except:
  - /^untagged/
script:
  - "./gradlew test"
before_deploy:
  - "./gradlew assembleProdRelease"
deploy:
  provider: releases
  edge: true
  api_key:
    secure: TE/ZGlEW/30cFz4CYkEzRKFj2E3T5pJXv9wd37md2a7MOd+QCEuEw7OAmS3Ya6VqZFQcGGGT2dDT1dVFWVOKyKW9rU3JrCX/F/lVCkFc2OIbmGMyJ3sP5swdl53Z+ECAyjC3fsex44tNjifH8rZ0UBMMGZOeVGqkkToin730GhQG6v1XREfSwJ5lSwsC59dR1zxpPzz36lDjaLTaJjLhQ7tOVQnJ7W//G2Nxjv28cGTr2GIwIn1dYNcyvy292Gd9rQz8zkInhJokqH+lLhnUxwj2Ce0xv3dCpDnqzlVkw5rBDPt24Y1/KYzKMTWNfqpS/wvI5as0Qq6m9Xd9GX1Nvadn36K5O/R5RtZA9DZaMQJ+Od16uzRTXcJUFgyCr4AuDsYpjXDF6EDReSWVkYEi4ZCMzXqL9m7KYwTF2zQrivTHPZ0TbX/qN32fs85ePaGOSYvV/vJLm+Yn6Lqt5ffdDBV5D+NRoyYES6nXXFHTKA0FcucZkeTqQVCtxTveyLUeNSEGPp+JYIEAxInb4joNKQWXEBVGMYViLAUNYaSdY8ZJa6KF1uhksZ8SRFQrvBav7ChZ8sPmM9d35+fSQZcoxdAtp2YT2IzUbqbdPCPcdGictiTXMgSWCxGuQGeXKOetOs79ZoctaWMfFn9sdB/fYlLAyvtvf6U11YJL1ri6wiQ=
  file: "RondoApp/build/outputs/apk/prod/release/RondoApp-prod-release.apk"
  name: "Android SDK $LEANPLUM_SDK_VERSION"
  tag: "$LEANPLUM_SDK_VERSION"
  on:
    branch: master
    condition: '-n "$LEANPLUM_SDK_VERSION"'
