language: android
android:
  components:
    - android-28
  before_install:
    - echo y | sdkmanager "platforms;android-27"
    - echo y | sdkmanager "platforms;android-28"
    - echo y | sdkmanager "build-tools;28.0.3"
