language: android

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - BUILD_API=31
    - BUILD_TOOLS=31.0.0
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/cmdline-tools/latest
    # PATH order is important, the 'emulator' script exists in more than one place
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

# Uncomment and remove lines in before_install when issue with JDK is resolved
# Check thread here: https://travis-ci.community/t/installing-oraclejdk-11-failed/13050/10
# jdk:
  # - oraclejdk11

android:
  components:
    - tools

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 11.0.12-open
  - sdk use java 11.0.12-open
  # Install cmdline-tools (older tools doesn't support Java 11)
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
  # Decrypt keystore
  - mkdir -p keystore
  - openssl aes-256-cbc -K $encrypted_3e25ea35f95b_key -iv $encrypted_3e25ea35f95b_iv -in signingkey.jks.enc -out keystore/signingkey.jks -d

before_script:
  # Install Android SDK
  - echo 'count=0' > /home/travis/.android/repositories.cfg # avoid harmless sdkmanager warning
  - echo y | ${TOOLS}/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "build-tools;$BUILD_TOOLS" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "platforms;android-$BUILD_API" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "extras;android;m2repository" >/dev/null

branches:
  except:
  - /^untagged/
script:
  - "./gradlew test"
before_deploy:
  - "./gradlew assembleProdRelease"
deploy:
  provider: releases
  edge: true
  api_key:
    secure: "B8oMG0JSJ/hEVVxexe2dP0of/PpaPwS8bi7e8gKNBtQkfbCxcNdFMMQbZsXD+bV09wfhiBt6piHsvaS0INf4vk+QhQ4BcPWT4O/4xkXm4DoIwKM1L5f1KESaot56yOKGjn0ny5EsDInPJcAJYpxcz5REIPbF0Jkw++gHO1TyqZ/UjY2t28oV8PcKoATMihArbSscMvBhxtJ0gzuXRZ6HsOZ6u/pHYbDpIzPAPkeOB0hmJOjHSdPTy31totaM2tS+Ef9+5E5M8vjFHY5dpFlC+Qn6K3XT7QiESfVz1/xfasfoLg0b9aAErbjZowaY3idvztZ1BeuRq//HHzswTaCXpW+nMw+9NCur6ksvGO7K5V79kzReQ+ARhOO8Q9h+E0V2xbrxY7W4qFz9LSXzJ6BEdrzWaUnflXhaQZfVpuzMa7kzcraEW2s4aTo5XEAXeuQowSiuEhfwqmN8bW2JODqjQQ33RAJRvgHe7RZtKhpv3hWuK1NuNiJCJL2CxH0sIXUSUSRvC9RWASTTY7gKaD8WH1oQWx1XVy1NalhT6vca2yZUoqeVvmBRZvjlthXfpxTGs7Ogfj2FFwEQJK0PV2mb1GTi6TbvLOkyosygra78addmSUwRP70ukP2TQYgHJDIB/ObzKTY72o6nRoEw4b/WxknjnQK+MnXmP8XbcrIdUiA="
  file: "RondoApp/build/outputs/apk/prod/release/RondoApp-prod-release.apk"
  name: "Android SDK $LEANPLUM_SDK_VERSION"
  tag: "$LEANPLUM_SDK_VERSION"
  on:
    branch: master
    condition: '-n "$LEANPLUM_SDK_VERSION"'

after_deploy:
  - GH_REPO=github.com/Leanplum/Rondo-Android.git
  - REPO_NAME=Rondo-Android
  - git clone https://${GH_REPO}
  - cd ${REPO_NAME}
  - git config user.email "travis@travis-ci.com"
  - git config user.name "travis"
  - git commit --allow-empty -m "Rondo released with SDK version $LEANPLUM_SDK_VERSION"
  - git push https://${ACCESS_TOKEN}@${GH_REPO} HEAD:master
